
global:
  storageClass: premium-rwo-retained
  clusterName: "test-2-cluster"
  cloud: gcp

tenantId: test-2
region: us

clickhouse:
  persistence:
    size: 200Gi

otelCollectorMetrics:
  config:
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: "signoz-spanmetrics-collector"
              scrape_interval: 60s
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_namespace]
                  action: keep
                  regex: test-2
                - source_labels:
                    [__meta_kubernetes_pod_annotation_apm_signoz_io_scrape]
                  action: keep
                  regex: true
                - source_labels:
                    [__meta_kubernetes_pod_annotation_apm_signoz_io_path]
                  action: replace
                  target_label: __metrics_path__
                  regex: (.+)
                - source_labels:
                    [
                      __meta_kubernetes_pod_ip,
                      __meta_kubernetes_pod_annotation_apm_signoz_io_port,
                    ]
                  action: replace
                  separator: ":"
                  target_label: __address__